baseurl = "https://fabiankuo.github.io/"
title = "Fabian Kuo"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Fabian Kuo"
disqusShortname = "Fabian"
# googleAnalytics = "XXX"
# pygmentsUseClasses = true
# pygmentsCodefences = true

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
tabWidth = 2

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = false

[author]
name = "Fabian"
profile = ""

[taxonomies]
tag = "tags"

[params]
mainSections = [ "post" ]
intro = true
headline = "Learning with Fabian"
description = "Join me on my life long learning journey"
github = "https://github.com/fabiankuo"
# gitlab = "https://gitlab.com/XXX"
linkedin = "https://linkedin.com/in/fabiankuo/"
#twitter = "https://twitter.com/XXX"
# stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
# facebook = "https://www.facebook.com/username"
email = "kuo_fabian@hotmail.com"
opengraph = true
#shareTwitter = true
# rss = true
#shareFacebook = true
shareLinkedIn = true
dateFormat = "Mon, Jan 2, 2006"
# exponeaJsUrl = ""
# exponeaTarget = ""
# exponeaToken = ""
# exponeaTrackVisits = false
# readingTime = true
# readingTimeText = "Estimated reading time:"
# fathomUrl = ""
# fathomSiteId = ""

#  [params.plausibleAnalytics]
#  domain = ""
#  serverURL = ""

[permalinks]
post = "/:year/:month/:day/:filename/"

[[menu.main]]
name = "Blog"
url = "/"
weight = 1

# [[menu.main]]
# name = "Projects"
# url = "/project/"
# weight = 2

# [[menu.main]]
# name = "Contact"
# url = "/page/contact/"
# weight = 3

# [[menu.main]]
# name = "About"
# url = "/page/about/"
# weight = 4
